adapter_path: gemma4_2b_amt_adapters
batch_size: 2
data: fabio_amt_dataset
grad_checkpoint: false
iters: 1000
learning_rate: 0.0001
lora_layers: 16
lora_parameters:
  alpha: 64
  dropout: 0.1
  rank: 32
  scale: 1.0
mask_prompt: true
max_seq_length: 1024
model: mlx-community/gemma-4-e2b-8bit
save_every: 100
steps_per_eval: 100
val: true
