"""Domain entities — objects with identity and lifecycle.

Entities are mutable and have methods that encapsulate their behavior.
All monetary values use Decimal for precision.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

from app.domain.trading.model.enums import (
    Side,
    SignalType,
    Source,
    SetupType,
    PositionStatus,
    CushionState,
)
from app.domain.trading.model.value_objects import OHLC


def _to_decimal(v: float | int | str | Decimal) -> Decimal:
    return Decimal(str(v)) if not isinstance(v, Decimal) else v


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------


@dataclass
class Signal:
    """A trade signal generated by an analysis service."""

    type: SignalType
    price: Decimal
    reason: str
    stop_loss: Decimal
    take_profit: Decimal
    timestamp: str
    setup: SetupType
    source: Source
    metadata: dict[str, Any] | None = None
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    @property
    def is_buy(self) -> bool:
        return self.type == SignalType.BUY

    @classmethod
    def create(
        cls,
        type: SignalType,
        price: float | Decimal,
        reason: str,
        stop_loss: float | Decimal,
        take_profit: float | Decimal,
        timestamp: str,
        setup: SetupType,
        source: Source,
        metadata: dict[str, Any] | None = None,
    ) -> "Signal":
        return cls(
            type=type,
            price=_to_decimal(price),
            reason=reason,
            stop_loss=_to_decimal(stop_loss),
            take_profit=_to_decimal(take_profit),
            timestamp=timestamp,
            setup=setup,
            source=source,
            metadata=metadata,
        )


# ---------------------------------------------------------------------------
# Position
# ---------------------------------------------------------------------------


@dataclass
class Position:
    """A trade position with full lifecycle management.

    Invariant: once status is CLOSED, no further mutations are allowed.
    """

    # Core fields
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: Side = Side.LONG
    source: Source = Source.AMT
    entry_price: Decimal = field(default_factory=lambda: Decimal("0"))
    size: Decimal = field(default_factory=lambda: Decimal("0"))
    stop_loss: Decimal = field(default_factory=lambda: Decimal("0"))
    take_profit: Decimal = field(default_factory=lambda: Decimal("0"))
    pnl: Decimal = field(default_factory=lambda: Decimal("0"))
    entry_time: str = ""
    status: PositionStatus = PositionStatus.OPEN
    exit_price: Decimal | None = None
    exit_time: str | None = None
    close_reason: str | None = None
    metadata: dict[str, Any] | None = None

    # Lifecycle state
    cushion_state: CushionState = CushionState.OPEN
    initial_stop: Decimal = field(default_factory=lambda: Decimal("0"))
    peak_profit: Decimal = field(default_factory=lambda: Decimal("0"))
    mae: Decimal = field(default_factory=lambda: Decimal("0"))
    mfe: Decimal = field(default_factory=lambda: Decimal("0"))
    tick_count: int = 0

    # Cushioning flags
    partial_taken: bool = False
    runner_active: bool = False
    breakeven_set: bool = False
    atr_trail_active: bool = False

    # Session context
    entry_cvd_direction: str = ""
    session_phase: str = ""
    is_expiry: bool = False
    applied_time_stop: float = 0.0

    # Scale-in (Fabio Rule 4: 40/30/30)
    scale_step: int = 1
    scale_confirm_price: Decimal = field(default_factory=lambda: Decimal("0"))
    scale_breakout_price: Decimal = field(default_factory=lambda: Decimal("0"))
    entry_lvns: list[float] = field(default_factory=list)

    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN

    @property
    def is_long(self) -> bool:
        return self.side == Side.LONG

    @property
    def is_short(self) -> bool:
        return self.side == Side.SHORT

    @property
    def risk_reward(self) -> float:
        """Calculate risk-reward ratio."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk == 0:
            return 0.0
        return float(reward / risk)

    def validate_cushion_transition(self, new_state: CushionState) -> bool:
        """Validate cushion state transitions: OPEN -> CUSHIONED -> TRAILING -> CLOSED."""
        valid_transitions: dict[CushionState, set[CushionState]] = {
            CushionState.OPEN: {CushionState.CUSHIONED, CushionState.CLOSED},
            CushionState.CUSHIONED: {CushionState.TRAILING, CushionState.CLOSED},
            CushionState.TRAILING: {CushionState.CLOSED},
            CushionState.CLOSED: set(),
        }
        return new_state in valid_transitions.get(self.cushion_state, set())

    def advance_cushion_state(self, new_state: CushionState) -> None:
        """Advance cushion state with validation."""
        if not self.validate_cushion_transition(new_state):
            import logging
            logging.getLogger(__name__).warning(
                "Invalid cushion transition %s -> %s for position %s",
                self.cushion_state.value, new_state.value, self.id,
            )
        self.cushion_state = new_state

    def update_pnl(self, current_price: float | Decimal) -> Decimal:
        """Recalculate unrealised PnL from current_price."""
        current = _to_decimal(current_price)
        diff = current - self.entry_price if self.side == Side.LONG else self.entry_price - current
        self.pnl = diff * self.size
        return self.pnl

    def move_stop_to_breakeven(self) -> None:
        """Move stop-loss to entry price."""
        self.stop_loss = self.entry_price

    def set_partial_taken(self, value: bool) -> None:
        """Set partial_taken flag and auto-transition cushion state."""
        self.partial_taken = value
        if value and self.cushion_state == CushionState.OPEN:
            self.advance_cushion_state(CushionState.CUSHIONED)

    def should_close(self, current_price: Decimal) -> tuple[bool, str]:
        """Check whether the position should be closed at current_price."""
        if self.side == Side.LONG:
            if current_price <= self.stop_loss:
                return True, "Stop Loss"
            if current_price >= self.take_profit:
                return True, "Take Profit (Full)"
        else:
            if current_price >= self.stop_loss:
                return True, "Stop Loss"
            if current_price <= self.take_profit:
                return True, "Take Profit (Full)"
        return False, ""

    def close(self, price: Decimal, time: str, reason: str) -> None:
        """Close the position at the given price."""
        self.update_pnl(price)
        self.status = PositionStatus.CLOSED
        self.exit_price = price
        self.exit_time = time
        self.close_reason = reason

    @staticmethod
    def open(
        symbol: str,
        side: Side,
        entry_price: float | Decimal,
        size: float | Decimal,
        stop_loss: float | Decimal,
        take_profit: float | Decimal,
    ) -> "Position":
        """Factory method to create an open position (convenience wrapper)."""
        return Position(
            symbol=symbol,
            side=side,
            entry_price=_to_decimal(entry_price),
            size=_to_decimal(size),
            stop_loss=_to_decimal(stop_loss),
            take_profit=_to_decimal(take_profit),
        )

    @staticmethod
    def from_signal(signal: Signal, symbol: str, size: Decimal) -> "Position":
        """Factory: create a new open position from a signal."""
        meta = signal.metadata or {}
        return Position(
            id=str(uuid.uuid4()),
            symbol=symbol,
            side=Side.LONG if signal.is_buy else Side.SHORT,
            source=signal.source,
            entry_price=signal.price,
            size=size,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            pnl=Decimal("0"),
            entry_time=signal.timestamp,
            status=PositionStatus.OPEN,
            metadata=signal.metadata,
            initial_stop=signal.stop_loss,
            session_phase=str(meta.get("session_phase", "")),
            is_expiry=bool(meta.get("is_expiry", False)),
        )
