"""Signal model — generated by strategy engine, consumed by execution engine."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from appv2.domain.enums.signal_type import SignalType, SetupType


@dataclass(frozen=True)
class Signal:
    """Trade signal produced by the strategy engine."""

    symbol: str  # Option contract symbol
    underlying_symbol: str  # Underlying futures symbol (for AMT reference)
    direction: SignalType
    setup_type: SetupType

    entry_price: float  # Expected entry price (LTP at signal time)
    stop_loss: float  # Absolute SL price
    take_profit: float  # Absolute TP price

    confidence: float  # 0.0–1.0
    market_state: str  # BALANCED, IMBALANCED, PROBING
    session_phase: str  # PRIMARY, MIDDAY, etc.

    timestamp: float = field(default_factory=time.time)  # Unix timestamp
    ttl_seconds: int = 600  # Time to live (default 10 min)

    # AMT context
    poc: float = 0.0
    vah: float = 0.0
    val: float = 0.0
    vwap: float = 0.0
    aggression_score: float = 0.0
    drive_number: int = 0

    # Options context
    strike_price: float = 0.0
    option_type: str = ""  # "CE" or "PE"
    expiry_date: str = ""
    delta: float = 0.0
    theta: float = 0.0

    # Gate results
    gates_passed: str = ""  # Comma-separated gate names
    gate_rejections: str = ""  # Comma-separated rejection reasons

    @property
    def is_expired(self) -> bool:
        return (time.time() - self.timestamp) > self.ttl_seconds

    @property
    def age_seconds(self) -> float:
        return time.time() - self.timestamp

    @property
    def risk(self) -> float:
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward(self) -> float:
        return abs(self.take_profit - self.entry_price)

    @property
    def risk_reward_ratio(self) -> float:
        if self.risk == 0:
            return 0.0
        return self.reward / self.risk

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "underlying_symbol": self.underlying_symbol,
            "direction": self.direction.value,
            "setup_type": self.setup_type.value,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "confidence": self.confidence,
            "market_state": self.market_state,
            "session_phase": self.session_phase,
            "timestamp": self.timestamp,
            "age_seconds": self.age_seconds,
            "is_expired": self.is_expired,
            "risk_reward_ratio": self.risk_reward_ratio,
            "poc": self.poc,
            "vah": self.vah,
            "val": self.val,
            "vwap": self.vwap,
            "option_type": self.option_type,
            "expiry_date": self.expiry_date,
        }
