"""Coordinator view port — the ONLY surface transport may touch. (REF-10)"""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ICoordinatorView(Protocol):
    """Read + lifecycle surface used by WS/routers. Engines stay private."""

    def snapshot(self, symbol: str) -> dict: ...
    def symbols(self) -> list: ...
    def switch_symbol(self, old: str, new: str) -> bool: ...
    def rescan(self) -> list: ...
    def unhalt_all(self) -> int: ...
