"""Domain entities — objects with identity and lifecycle.

Entities are mutable and have methods that encapsulate their behavior.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, overload

from app.domain.trading.models.enums import (
    Side, SignalType, Source, SetupType, PositionStatus,
)


def _to_decimal(value: float | int | str | Decimal) -> Decimal:
    """Convert various numeric types to Decimal for precise financial calculations."""
    if isinstance(value, Decimal):
        return value
    return Decimal(str(value))


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """A trade signal generated by an analysis service.
    
    All monetary values use Decimal for precision in financial calculations.
    Use Signal.create() factory for convenient float-to-Decimal conversion.
    """
    type: SignalType
    price: Decimal
    reason: str
    stop_loss: Decimal
    take_profit: Decimal
    timestamp: str
    setup: SetupType
    source: Source
    metadata: dict[str, Any] | None = None
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    @property
    def is_buy(self) -> bool:
        return self.type == SignalType.BUY

    @classmethod
    def create(
        cls,
        type: SignalType,
        price: float | Decimal,
        reason: str,
        stop_loss: float | Decimal,
        take_profit: float | Decimal,
        timestamp: str,
        setup: SetupType,
        source: Source,
        metadata: dict[str, Any] | None = None,
    ) -> "Signal":
        """Factory method that accepts float or Decimal for monetary values."""
        return cls(
            type=type,
            price=_to_decimal(price),
            reason=reason,
            stop_loss=_to_decimal(stop_loss),
            take_profit=_to_decimal(take_profit),
            timestamp=timestamp,
            setup=setup,
            source=source,
            metadata=metadata,
        )


# ---------------------------------------------------------------------------
# Position
# ---------------------------------------------------------------------------

@dataclass
class Position:
    """A trade position with full lifecycle management.

    Invariant: once ``status`` is CLOSED, no further mutations are allowed.
    
    All monetary values use Decimal for precision in financial calculations.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: Side = Side.LONG
    source: Source = Source.AMT
    entry_price: Decimal = field(default_factory=lambda: Decimal("0"))
    size: Decimal = field(default_factory=lambda: Decimal("0"))
    stop_loss: Decimal = field(default_factory=lambda: Decimal("0"))
    take_profit: Decimal = field(default_factory=lambda: Decimal("0"))
    pnl: Decimal = field(default_factory=lambda: Decimal("0"))
    entry_time: str = ""
    status: PositionStatus = PositionStatus.OPEN
    exit_price: Decimal | None = None
    exit_time: str | None = None
    close_reason: str | None = None
    metadata: dict[str, Any] | None = None

    # ----- behaviour -----

    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN

    def update_pnl(self, current_price) -> Decimal:
        """Recalculate unrealised PnL from *current_price*."""
        from decimal import Decimal as D
        
        # Ensure both prices are Decimal for calculation
        if not isinstance(current_price, D):
            current_price = D(str(round(float(current_price), 6)))
        entry = self.entry_price
        if not isinstance(entry, D):
            entry = D(str(round(float(entry), 6)))
        
        diff = (
            current_price - entry
            if self.side == Side.LONG
            else entry - current_price
        )
        # Ensure size is Decimal for multiplication
        size = self.size
        if not isinstance(size, D):
            size = D(str(float(size)))
        self.pnl = diff * size
        return self.pnl

    def move_stop_to_breakeven(self) -> None:
        """Move stop-loss to entry price (break-even)."""
        self.stop_loss = self.entry_price

    def should_close(self, current_price: Decimal) -> tuple[bool, str]:
        """Check whether the position should be closed at *current_price*."""
        if self.side == Side.LONG:
            if current_price <= self.stop_loss:
                return True, "Stop Loss"
            if current_price >= self.take_profit:
                return True, "Take Profit (Full)"
        else:
            if current_price >= self.stop_loss:
                return True, "Stop Loss"
            if current_price <= self.take_profit:
                return True, "Take Profit (Full)"
        return False, ""

    def close(self, price: Decimal, time: str, reason: str) -> None:
        """Close the position at the given *price*."""
        self.update_pnl(price)
        self.status = PositionStatus.CLOSED
        self.exit_price = price
        self.exit_time = time
        self.close_reason = reason

    @staticmethod
    def from_signal(signal: Signal, symbol: str, size: Decimal) -> "Position":
        """Factory: create a new open position from a signal."""
        return Position(
            id=str(uuid.uuid4()),
            symbol=symbol,
            side=Side.LONG if signal.is_buy else Side.SHORT,
            source=signal.source,
            entry_price=signal.price,
            size=size,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            pnl=Decimal("0"),
            entry_time=signal.timestamp,
            status=PositionStatus.OPEN,
            metadata=signal.metadata,
        )
