"""Domain entities — objects with identity and lifecycle.

Entities are mutable and have methods that encapsulate their behavior.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any

from app.domain.trading.models.enums import (
    Side, SignalType, Source, SetupType, PositionStatus,
)


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """A trade signal generated by an analysis service."""
    type: SignalType
    price: float
    reason: str
    stop_loss: float
    take_profit: float
    timestamp: str
    setup: SetupType
    source: Source
    metadata: dict[str, Any] | None = None

    @property
    def is_buy(self) -> bool:
        return self.type == SignalType.BUY


# ---------------------------------------------------------------------------
# Position
# ---------------------------------------------------------------------------

@dataclass
class Position:
    """A trade position with full lifecycle management.

    Invariant: once ``status`` is CLOSED, no further mutations are allowed.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: Side = Side.LONG
    source: Source = Source.AMT
    entry_price: float = 0.0
    size: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    pnl: float = 0.0
    entry_time: str = ""
    status: PositionStatus = PositionStatus.OPEN
    exit_price: float | None = None
    exit_time: str | None = None
    close_reason: str | None = None
    metadata: dict[str, Any] | None = None

    # ----- behaviour -----

    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN

    def update_pnl(self, current_price: float) -> float:
        """Recalculate unrealised PnL from *current_price*."""
        diff = (
            current_price - self.entry_price
            if self.side == Side.LONG
            else self.entry_price - current_price
        )
        self.pnl = diff * self.size
        return self.pnl

    def move_stop_to_breakeven(self) -> None:
        """Move stop-loss to entry price (break-even)."""
        self.stop_loss = self.entry_price

    def should_close(self, current_price: float) -> tuple[bool, str]:
        """Check whether the position should be closed at *current_price*."""
        if self.side == Side.LONG:
            if current_price <= self.stop_loss:
                return True, "Stop Loss"
            if current_price >= self.take_profit:
                return True, "Take Profit (Full)"
        else:
            if current_price >= self.stop_loss:
                return True, "Stop Loss"
            if current_price <= self.take_profit:
                return True, "Take Profit (Full)"
        return False, ""

    def close(self, price: float, time: str, reason: str) -> None:
        """Close the position at the given *price*."""
        self.update_pnl(price)
        self.status = PositionStatus.CLOSED
        self.exit_price = price
        self.exit_time = time
        self.close_reason = reason

    @staticmethod
    def from_signal(signal: Signal, symbol: str, size: float) -> "Position":
        """Factory: create a new open position from a signal."""
        return Position(
            id=str(uuid.uuid4()),
            symbol=symbol,
            side=Side.LONG if signal.is_buy else Side.SHORT,
            source=signal.source,
            entry_price=signal.price,
            size=size,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            pnl=0.0,
            entry_time=signal.timestamp,
            status=PositionStatus.OPEN,
            metadata=signal.metadata,
        )
