"""Domain entities — objects with identity and lifecycle.

Entities are mutable and have methods that encapsulate their behavior.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, overload

from app.domain.trading.models.enums import (
    Side,
    SignalType,
    Source,
    SetupType,
    PositionStatus,
    CushionState,
)
from app.domain.services.decimal_utils import to_decimal


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------


@dataclass
class Signal:
    """A trade signal generated by an analysis service.

    All monetary values use Decimal for precision in financial calculations.
    Use Signal.create() factory for convenient float-to-Decimal conversion.
    """

    type: SignalType
    price: Decimal
    reason: str
    stop_loss: Decimal
    take_profit: Decimal
    timestamp: str
    setup: SetupType
    source: Source
    metadata: dict[str, Any] | None = None
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    @property
    def is_buy(self) -> bool:
        return self.type == SignalType.BUY

    @classmethod
    def create(
        cls,
        type: SignalType,
        price: float | Decimal,
        reason: str,
        stop_loss: float | Decimal,
        take_profit: float | Decimal,
        timestamp: str,
        setup: SetupType,
        source: Source,
        metadata: dict[str, Any] | None = None,
    ) -> "Signal":
        """Factory method that accepts float or Decimal for monetary values."""
        return cls(
            type=type,
            price=to_decimal(price),
            reason=reason,
            stop_loss=to_decimal(stop_loss),
            take_profit=to_decimal(take_profit),
            timestamp=timestamp,
            setup=setup,
            source=source,
            metadata=metadata,
        )


# ---------------------------------------------------------------------------
# Position
# ---------------------------------------------------------------------------


@dataclass
class Position:
    """A trade position with full lifecycle management.

    Invariant: once ``status`` is CLOSED, no further mutations are allowed.

    All monetary values use Decimal for precision in financial calculations.
    """

    # ----- core fields -----

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: Side = Side.LONG
    source: Source = Source.AMT
    entry_price: Decimal = field(default_factory=lambda: Decimal("0"))
    size: Decimal = field(default_factory=lambda: Decimal("0"))
    stop_loss: Decimal = field(default_factory=lambda: Decimal("0"))
    take_profit: Decimal = field(default_factory=lambda: Decimal("0"))
    pnl: Decimal = field(default_factory=lambda: Decimal("0"))
    entry_time: str = ""
    status: PositionStatus = PositionStatus.OPEN
    exit_price: Decimal | None = None
    exit_time: str | None = None
    close_reason: str | None = None
    metadata: dict[str, Any] | None = None

    # ── Lifecycle State ─────────────────────────────────────
    cushion_state: CushionState = CushionState.OPEN
    initial_stop: Decimal = field(default_factory=lambda: Decimal("0"))    # Original SL for R-multiple calc
    peak_profit: Decimal = field(default_factory=lambda: Decimal("0"))    # Highest unrealized profit (price units)
    mae: Decimal = field(default_factory=lambda: Decimal("0"))            # Maximum Adverse Excursion
    mfe: Decimal = field(default_factory=lambda: Decimal("0"))            # Maximum Favorable Excursion
    tick_count: int = 0                                                    # Ticks since entry

    # ── Cushioning Flags ────────────────────────────────────
    partial_taken: bool = False         # True after first partial TP
    runner_active: bool = False         # True when runner portion trailing
    breakeven_set: bool = False         # True once SL moved to entry
    atr_trail_active: bool = False      # True once ATR trail armed

    # ── Session Context ─────────────────────────────────────
    entry_cvd_direction: str = ""       # CVD confirmation direction
    session_phase: str = ""             # "MORNING" or "AFTERNOON"
    is_expiry: bool = False             # True on options expiry day
    applied_time_stop: float = 0.0     # Computed session time stop (monotonic)

    # ── Scale-In (Fabio Rule 4: 40/30/30) ──────────────────
    scale_step: int = 1                 # 1=initial, 2=confirmation, 3=breakout
    scale_confirm_price: Decimal = field(default_factory=lambda: Decimal("0"))
    scale_breakout_price: Decimal = field(default_factory=lambda: Decimal("0"))

    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN

    def validate_cushion_transition(self, new_state: CushionState) -> bool:
        """Validate cushion state transitions: OPEN → CUSHIONED → TRAILING → CLOSED."""
        valid_transitions: dict[CushionState, set[CushionState]] = {
            CushionState.OPEN: {CushionState.CUSHIONED, CushionState.CLOSED},
            CushionState.CUSHIONED: {CushionState.TRAILING, CushionState.CLOSED},
            CushionState.TRAILING: {CushionState.CLOSED},
            CushionState.CLOSED: set(),
        }
        return new_state in valid_transitions.get(self.cushion_state, set())

    def advance_cushion_state(self, new_state: CushionState) -> None:
        """Advance cushion state with validation. Logs warning on invalid transition."""
        if not self.validate_cushion_transition(new_state):
            import logging
            logging.getLogger(__name__).warning(
                "Invalid cushion transition %s → %s for position %s",
                self.cushion_state.value, new_state.value, self.id
            )
        self.cushion_state = new_state

    def update_pnl(self, current_price) -> Decimal:
        """Recalculate unrealised PnL from *current_price*."""
        # Use domain decimal utility for consistent precision
        current = to_decimal(current_price)
        entry = to_decimal(self.entry_price)
        size = to_decimal(self.size)

        diff = current - entry if self.side == Side.LONG else entry - current
        self.pnl = diff * size
        return self.pnl

    def move_stop_to_breakeven(self) -> None:
        """Move stop-loss to entry price (break-even)."""
        self.stop_loss = self.entry_price

    def set_partial_taken(self, value: bool) -> None:
        """Set partial_taken flag. Compatibility shim for test API."""
        self.partial_taken = value

    def should_close(self, current_price: Decimal) -> tuple[bool, str]:
        """Check whether the position should be closed at *current_price*."""
        if self.side == Side.LONG:
            if current_price <= self.stop_loss:
                return True, "Stop Loss"
            if current_price >= self.take_profit:
                return True, "Take Profit (Full)"
        else:
            if current_price >= self.stop_loss:
                return True, "Stop Loss"
            if current_price <= self.take_profit:
                return True, "Take Profit (Full)"
        return False, ""

    def close(self, price: Decimal, time: str, reason: str) -> None:
        """Close the position at the given *price*."""
        self.update_pnl(price)
        self.status = PositionStatus.CLOSED
        self.exit_price = price
        self.exit_time = time
        self.close_reason = reason

    @staticmethod
    def from_signal(signal: Signal, symbol: str, size: Decimal) -> "Position":
        """Factory: create a new open position from a signal."""
        meta = signal.metadata or {}
        return Position(
            id=str(uuid.uuid4()),
            symbol=symbol,
            side=Side.LONG if signal.is_buy else Side.SHORT,
            source=signal.source,
            entry_price=signal.price,
            size=size,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            pnl=Decimal("0"),
            entry_time=signal.timestamp,
            status=PositionStatus.OPEN,
            metadata=signal.metadata,
            initial_stop=signal.stop_loss,
            session_phase=str(meta.get("session_phase", "")),
            is_expiry=bool(meta.get("is_expiry", False)),
        )
